version: "3.8"

services:
  postgres:
    image: postgres:14.5-alpine
    working_dir: /application
    volumes:
      - postgres:/data/postgres
      - .:/application
    environment:
      - PGDATA=/data/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tira_time
      - PGHOST=localhost
      - PGPORT=5432
    ports:
      - 5432:5432

  web:
    build: .
    ports:
      - 3000:3000
    container_name: tira_time_backend
    command: npm run start:dev
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=tira_time

volumes:
  postgres:
